apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Zharend/argocd-test-repo.git
              revision: HEAD
              directories:
              - path: "envs/*/*"
          - clusters:
              selector:
                matchLabels:
                  kubernetes.io/environment: "{{path[1]}}"
  template:
    metadata:
      name: '{{path[1]}}-{{path.basename}}'
      namespace: cre-core
    spec:
      project: default
      source:
        repoURL: https://github.com/Zharend/argocd-test-repo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: "{{server}}"
        namespace: cre-core
